language: elixir
elixir:
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
otp_release:
  - 21.1
  - 20.3
  - 19.3
  - 18.3
  
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.5
      otp_release: 21.1
    - elixir: 1.4
      otp_release: 21.1
    - elixir: 1.3
      otp_release: 21.1
    - elixir: 1.3
      otp_release: 20.3
script: mix test && mix credo
